### ISSUE TITLE
📇 Tracker: fusion core dependencies

### ISSUE THREAD

**Issue by ken-mellem** [equinor/fusion-project-portal#324]
## Dependencies

See Roadmap/Progress map in [Miro](https://miro.com/app/board/uXjVMqPIWW4=/)

### Process

The tasks below will need to go through a triage with PO/SA whom can set priority.

### Notification

- [ ] Notification: Notification actions are scoped to the origin of the notification

### Work Assigned

- [ ] Work Assigned: Align work item data
- [ ] Work Assigned: Identify more Categories that should be available

### Service message

- [ ] Show Scoped portal messages

### Pinned Apps

- [ ] Display favorites cross devices
- [ ] Display favorites loaded fusion service
- [ ] Update design to align with fusion pinned apps
